### ISSUE TITLE
The remote party closed the WebSocket connection without completing the close handshake

### ISSUE THREAD

**Issue by MuhammadUsamaAhsan** [tpeczek/Demo.AspNetCore.WebSockets#5]
While deploying project on IIS or anyother server this error occurs 

_**System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake. ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at Lib.AspNetCore.WebSocketsCompression.Net.WebSockets.CompressionWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken, Boolean throwOnPrematureClosure)
   at Lib.AspNetCore.WebSocketsCompression.Net.WebSockets.CompressionWebSocket.InternalReceiveAsync(ArraySegment`1 payloadBuffer, CancellationToken cancellationToken)
   at Lib.AspNetCore.WebSocketsCompression.Net.WebSockets.CompressionWebSocket.InternalReceiveAsync(ArraySegment`1 payloadBuffer, CancellationToken cancellationToken)
   at Demo.AspNetCore.WebSockets.Infrastructure.WebSocketConnection.ReceiveMessagesUntilCloseAsync()**_

**Comment by tpeczek** [comment]
Yes, WebSocket extensions (in this particular case compression) are not supported by IIS module for ASP.NET Core. This is why there is no IIS profile in `launchSettings.json`. Hopefully this will change when there will be native support for WebScoket compression in ASP.NET Core (#4). For now, if you would like to run this project in IIS hoting scenario, you have to remove the compression from code.

**Comment by MuhammadUsamaAhsan** [comment]
Dear Tomasz
Can you please guide me with below function how i can remove compression
from that

  public Task SendAsync(byte[] message, CancellationToken cancellationToken)
        {
            return
_webSocketCompressionProvider.CompressBinaryMessageAsync(_webSocket,
message, cancellationToken);
        }

**Comment by tpeczek** [comment]
It should look more less like this (haven't tested).

```
public Task SendAsync(byte[] message, CancellationToken cancellationToken)
{
	if (_webSocket.State == WebSocketState.Open)
	{
		ArraySegment<byte> messageSegment = new ArraySegment<byte>(message, 0, message.Length);

		return _webSocket.SendAsync(messageSegment, WebSocketMessageType.Binary, true, cancellationToken);
	}

        return Task.CompletedTask;
}
```

**Comment by MuhammadUsamaAhsan** [comment]
Dear Tomasz,
I have already done that thankyou so much for you generous guidance
Right now I am stucked in decompressing a message
I have seen techniques but don't find them useful to integrate them in code

If you can kindly help me with decompressing of message
following is function in which m stucked















*while (webSocketReceiveResult.MessageType != WebSocketMessageType.Close)
              {                    if (webSocketReceiveResult.MessageType
== WebSocketMessageType.Binary)                    {
byte[] webSocketMessage = await
_webSocketCompressionProvider.DecompressBinaryMessageAsync(_webSocket,
webSocketReceiveResult, receivePayloadBuffer);
OnReceiveBinary(webSocketMessage);                    }
else                    {                        string webSocketMessage =
await _webSocketCompressionProvider.DecompressTextMessageAsync(_webSocket,
webSocketReceiveResult, receivePayloadBuffer);
OnReceiveText(webSocketMessage);                    }
webSocketReceiveResult = await _webSocket.ReceiveAsync(new
ArraySegment<byte>(receivePayloadBuffer), CancellationToken.None);
      }*

**Comment by tpeczek** [comment]
Sure, I can rework that snippet in a free moment (which will be probably similar time tomorrow).

If you want to take a stub at it meantime, you can take a look [here](https://github.com/tpeczek/Lib.AspNetCore.WebSocketsCompression/blob/main/Lib.AspNetCore.WebSocketsCompression/Providers/WebSocketIdentityCompressionProvider.cs) and cut the code for `compressed == false` paths - this is what you need.

**Comment by tpeczek** [comment]
Sorry it took so long, but responsibilities...

The one below should be a simple working version, it can be further optimized when it comes to memory usage if you wish to give it some love.

```cs
public async Task ReceiveMessagesUntilCloseAsync()
{
	try
	{
		byte[] receivePayloadBuffer = new byte[_receivePayloadBufferSize];
		WebSocketReceiveResult webSocketReceiveResult = await _webSocket.ReceiveAsync(new ArraySegment<byte>(receivePayloadBuffer), CancellationToken.None);
		while (webSocketReceiveResult.MessageType != WebSocketMessageType.Close)
		{
			byte[] webSocketMessagePayload = await ReceiveMessagePayloadAsync(webSocketReceiveResult, receivePayloadBuffer);
			
			if (webSocketReceiveResult.MessageType == WebSocketMessageType.Binary)
			{
				OnReceiveBinary(webSocketMessagePayload);
			}
			else
			{
				OnReceiveText(Encoding.UTF8.GetString(webSocketMessagePayload));
			}

			webSocketReceiveResult = await _webSocket.ReceiveAsync(new ArraySegment<byte>(receivePayloadBuffer), CancellationToken.None);
		}

		CloseStatus = webSocketReceiveResult.CloseStatus.Value;
		CloseStatusDescription = webSocketReceiveResult.CloseStatusDescription;
	}
	catch (WebSocketException wsex) when (wsex.WebSocketErrorCode == WebSocketError.ConnectionClosedPrematurely)
	{ }
}

private async Task<byte[]> ReceiveMessagePayloadAsync(WebSocketReceiveResult webSocketReceiveResult, byte[] receivePayloadBuffer)
{
	byte[] messagePayload = null;

	if (webSocketReceiveResult.EndOfMessage)
	{
		messagePayload = new byte[webSocketReceiveResult.Count];
		Array.Copy(receivePayloadBuffer, messagePayload, webSocketReceiveResult.Count);
	}
	else
	{
		using (MemoryStream messagePayloadStream = new MemoryStream())
		{
			messagePayloadStream.Write(receivePayloadBuffer, 0, webSocketReceiveResult.Count);
			while (!webSocketReceiveResult.EndOfMessage)
			{
				webSocketReceiveResult = await webSocket.ReceiveAsync(new ArraySegment<byte>(receivePayloadBuffer), CancellationToken.None);
				messagePayloadStream.Write(receivePayloadBuffer, 0, webSocketReceiveResult.Count);
			}

			messagePayload = messagePayloadStream.ToArray();
		}
	}

	return messagePayload;
}
```

**Comment by MuhammadUsamaAhsan** [comment]
Dear Tomasz,
Thankyou so much, and yes i will look into this code.
Thanks Alot for your generous guidance clears a whole lot of my concepts
really appreciated
