### ISSUE TITLE
Using `WebSocketConnection` along with time consuming dependencies.

### ISSUE THREAD

**Issue by PROxZIMA** [tpeczek/Demo.AspNetCore.WebSockets#8]
Hi @tpeczek, hope you are doing well. I'm trying to use your WebSocket implementation with some time-consuming dependencies.

I have a `IConsumer` service and a `IManager` service, which I used to use along with a controller. But since some of the `IConsumer` service's methods take >120s to complete, I decided to use websockets.

I tried to inject `IManager` as a DI in `WebSocketConnection` but it eventually makes the Connection far less reusable.

What's the appropriate way of using the `IManager` along with the `WebSocketConnection` or simply using the Connection in a consumer? I know this is not completely related to your example. It's more like an architectural thing but I'm still new to the .NET world :)

**Comment by PROxZIMA** [comment]
I eventually came up with the following flow.

```cs
public interface IWebSocketConnectionsHandler
{
    Task OnReceiveText(WebSocketConnection connection, string message);
}
```

```cs
public class WebSocketConnectionsHandler : IWebSocketConnectionsHandler
{
    private readonly IManager _manager;
    public WebSocketConnectionsHandler(IManager manager)
    {
        _manager = IManager;
    }

    public async Task OnReceiveText(WebSocketConnection connection, string message)
    {
        var data = JsonSerializer.Deserialize<Connection>(message);
        switch (data.Type)
        {
            case "GetConsumer":
                ConnectionModel model = await _manager.getConsumer(data);
                await connection.SendAsync(model, CancellationToken.None);
                break;
            case "UpdateConsumer":
                ConnectionModel status = await _manager.updateConsumer(data);
                await connection.SendAsync(model, CancellationToken.None);
                break;
            default:
                await connection.SendAsync("", CancellationToken.None);
                break;
        }
    }
}
```

`WebSocketConnectionsMiddleware.Invoke`
```cs
public async Task Invoke(HttpContext context, IWebSocketConnectionsHandler connectionsHandler)
{
    ...
    WebSocketConnection webSocketConnection = new WebSocketConnection(...);
    webSocketConnection.ReceiveText += async (sender, message) =>
    {
        await connectionsHandler.OnReceiveText((WebSocketConnection)sender, message);
    };
    ...
}
```

`Startup.cs`
```cs
services.AddScoped<IWebSocketConnectionsHandler, WebSocketConnectionsHandler>();
```

I think this is good enough as of now. `Handler.OnReceiveText` can be improved too.

Also found this article https://radu-matei.com/blog/aspnet-core-websockets-middleware/. Above answer can be improved using the suggested method.

**Comment by tpeczek** [comment]
Hi @PROxZIMA,

Yes, your approach should get the work done in a simple way.

From perspective of how this demo is constructed, it would be about creating a different implementation of `WebSocketConnectionsService`.
